export enum ENV_KEYS {
  ENVIRONMENT = 'ENVIRONMENT',
  APP_PORT = 'APP_PORT',
  YOUTUBE_API_KEY = 'YOUTUBE_API_KEY',
  YOUTUBE_API_BASE_URL = 'YOUTUBE_API_BASE_URL',
  MOVIE_DB_BASE_URL = 'MOVIE_DB_BASE_URL',
  MOVIE_DB_API_KEY = 'MOVIE_DB_API_KEY',
}
